[project]
name = "corin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy==2.4.1",
    "polars==0.20.31",
    "huggingface-hub==0.23.4",
    "pytest==9.0.2",
    "torch==2.10.0",
]
